title: "Jupyter Notebooks for chapters 6 and 7"
author: "Jorge Alda"
execute:
    execute_notebooks: "off"
    
repository:
    url: "https://github.com/Jorge-Alda/SMEFT19"
    path_to_book: "jupyter"
    branch: "gh-pages"