name: test
dependencies:
    - iminuit=1.3.10
    - particle=0.14.1
    - PyYAML=5.4
    - xgboost=1.0.2
    - shap=0.35.0
    - ipykernel
    - pip:
        - flavio==2.3.1
        - wilson==2.0
        - git+https://github.com/Jorge-Alda/smelli.git@more_bins#egg=smelli
        - git+https://github.com/Jorge-Alda/parscanning.git@v1.0#egg=parscanning
        - git+https://github.com/Jorge-Alda/texfig.git#egg=texfig
        - "-e git+https://github.com/Jorge-Alda/SMEFT19.git@dev#egg=SMEFT19"